### ISSUE TITLE
uploading a new version?

### ISSUE THREAD

**Issue by Javran** [RaphaelJ/friday-devil#4]
it seems `0.1.1.1` is still having transformers version upper bound set to `< 5` while it's `< 6` in master branch. it'll be appreciated if a new version can be uploaded.

meanwhile as a workaround for stack users: you can merge the following yaml in order to use current master branch as one of your package's dependency.

```yaml
packages:
- location:
    git: https://github.com/RaphaelJ/friday-devil.git
    commit: 73181586307a4db93302bfeb9af9ded615e60a07
  extra-dep: true
```
